execute as @s[tag=hat0] unless entity @s[nbt={Inventory:[{Slot:5b, id:"minecraft:air"}]}] run item replace entity @s armor.head with air
execute as @s[tag=hat1] unless entity @s[nbt={Inventory:[{Slot:5b, id:"minecraft:glass"}]}] run item replace entity @s armor.head with glass
execute as @s[tag=hat2] unless entity @s[nbt={Inventory:[{Slot:5b, id:"minecraft:creeper_head"}]}] run item replace entity @s armor.head with creeper_head
execute as @s[tag=hat3] unless entity @s[nbt={Inventory:[{Slot:5b, id:"minecraft:dragon_head"}]}] run item replace entity @s armor.head with dragon_head
execute as @s[tag=hat4] unless entity @s[nbt={Inventory:[{Slot:5b, id:"minecraft:redstone_block"}]}] run item replace entity @s armor.head with redstone_block
execute as @s[tag=hat5] unless entity @s[nbt={Inventory:[{Slot:5b, id:"minecraft:wither_skeleton_skull"}]}] run item replace entity @s armor.head with wither_skeleton_skull
execute as @s[tag=hat6] unless entity @s[nbt={Inventory:[{Slot:5b, id:"minecraft:skeleton_skull"}]}] run item replace entity @s armor.head with skeleton_skull
execute as @s[tag=hat7] unless entity @s[nbt={Inventory:[{Slot:5b, id:"minecraft:lightning_rod"}]}] run item replace entity @s armor.head with lightning_rod
execute as @s[tag=hat8] unless entity @s[nbt={Inventory:[{Slot:5b, id:"minecraft:end_rod"}]}] run item replace entity @s armor.head with end_rod
execute as @s[tag=hat9] unless entity @s[nbt={Inventory:[{Slot:5b, id:"minecraft:target"}]}] run item replace entity @s armor.head with target
execute as @s[tag=hat10] unless entity @s[nbt={Inventory:[{Slot:5b, id:"minecraft:tnt"}]}] run item replace entity @s armor.head with tnt
execute as @s[tag=hat11] unless entity @s[nbt={Inventory:[{Slot:5b, id:"minecraft:slime_block"}]}] run item replace entity @s armor.head with slime_block
execute as @s[tag=hat12] unless entity @s[nbt={Inventory:[{Slot:5b, id:"minecraft:observer"}]}] run item replace entity @s armor.head with observer
